[[redirects]]
  from = "/cors-proxy/*"
  to = "https://www.metaweather.com/api/location/search"
  status = 301
  query = {lattlong = ":lattlong"}
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

