[[redirects]]
  from = "/cors-proxy/*"
  to = "https://www.metaweather.com/api/location/search/"
  status = 200
  query = {lattlong = ":lattlong"}
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
  
[[redirects]]
from = "/cors-data/*"
to = "https://www.metaweather.com/:splat"
status = 200
force = true
headers = {Access-Control-Allow-Origin = "*"}

